# -*- coding: utf-8 -*-
"""C-108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C68Y7iziSjYWljU2A8Q2zA9mJcW_Ola5
"""

from google.colab import files
import statistics
import plotly.figure_factory as ff
import pandas as pd
import csv
file_toload=files.upload()
df=pd.read_csv("height-weight.csv")

height_list=df["Height(Inches)"].to_list()
weight_list=df["Weight(Pounds)"].to_list()

height_mean=statistics.mean(height_list)
weight_mean=statistics.mean(weight_list)
height_median=statistics.median(height_list)
weight_median=statistics.median(weight_list)
height_mode=statistics.mode(height_list)
weight_mode=statistics.mode(weight_list)
print(f'Mean of height is {statistics.mean(height_list)}')
print(f'Median of height is {statistics.median(height_list)}')
print(f'Mode of height is {statistics.mode(height_list)}')
print(f'Mean of weight is {statistics.mean(weight_list)}')
print(f'Median of weight is {statistics.median(weight_list)}')
print(f'Mode of weight is {statistics.mode(weight_list)}')